### ISSUE TITLE
SX1262 shows a lower SNR than SX1276 based boards

### ISSUE THREAD

**Issue by drewsed** [meshtastic/Meshtastic-device#332]
Hi,

I recently received my two TBeam 1.1 with the new SX1262 LoRa module and it seems that the signal strength calculation is somehow different than with SX1276.

Board Link: https://www.aliexpress.com/item/LILYGO-TTGO-T-Beam-V1-1-SX1262-LORA-868-915MHZ-ESP32-WiFi-Wireless-Bluetooth-Module-GPS/4001287221970.html?spm=a2g0s.9042311.0.0.46b94c4dJdZvPj

Aso mentioned on forum:
https://meshtastic.discourse.group/t/tbeam-with-sx1262/972/18?u=drewsed

**Comment by geeksville** [comment]
hmm interesting.  I just tried two different SX1262 based boards receiving from a old TBEAM.  On both boards the RXSNR for the packet was 7dBm.  

One receiver was a SX1262 TBEAM and the other was a NRF52840+official sematech SX1262 eval board.  So it looks like the receive RX performance is pretty close between the TBEAM and the ref board.  I also checked the getSNR function and its implementation matches the SX1262 datasheet, so I think it is calculating correctly.

I'll now need to check the old SX1278/RF95 getsnr function, which would have declared about 10dBm for this test.  Perhaps it is wrong?

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/tbeam-with-sx1262/972/25

**Comment by mc-hamster** [comment]
@drewsed Could you retest this with the latest firmware? I fixed a setting in our use of the sx1262 library that may have caused the problem you described. 

https://github.com/meshtastic/Meshtastic-device/issues/466

**Comment by drewsed** [comment]
@mc-hamster sure, but unfortunately it did not solve the issue for me. I did the update via bt, so do you think things will change if i do a clean serial flash?

My tbeams (1.1.7) show a signal strength of 77%, 80% and 85%, while both heltecs (1.1.7) show 97%, 100% and 100%

**Comment by mc-hamster** [comment]
Hmm ...

The receive signal strength should not have anything to do with the configuration. It’s all hard coded. 

I’ll keep an eye out. Could also be the scale is being reported different. 

Worth a shot. Thanks for retesting.

**Comment by mc-hamster** [comment]
More data.

On a sx1276, I got measured an rssi of -59 with a snr of 5. My noise floor is at -87.

With a signal attenuator attached to a device, I got an rssi of -94 and a snr of 5.5 with the same noise floor.

With the signal attenuator attached, I should have gotten a negative snr from the device. 

This suggests to me that there's a bug in the sx127x library.

Comparing the sx126x and sx127x libraries, they compute the SNR slightly different.

float SX126x::getSNR() {
  // check active modem
  if(getPacketType() != SX126X_PACKET_TYPE_LORA) {
    return(ERR_WRONG_MODEM);
  }

  // get last packet SNR from packet status
  uint32_t packetStatus = getPacketStatus();
  uint8_t snrPkt = (packetStatus >> 8) & 0xFF;
  if(snrPkt < 128) {
    return(snrPkt/4.0);
  } else {
    return((snrPkt - 256)/4.0);
  }
}


float SX127x::getSNR() {
  // check active modem
  if(getActiveModem() != SX127X_LORA) {
    return(0);
  }

  // get SNR value
  int8_t rawSNR = (int8_t)_mod->SPIgetRegValue(SX127X_REG_PKT_SNR_VALUE);
  return(rawSNR / 4.0);
}

**Comment by mc-hamster** [comment]
The sx127x data sheet on page 112 describes the snr value register as:

```
Estimation of SNR on last packet received.In two’s compliment
format mutiplied by 4.
```

The sx126x data sheets on page 97 describes the snr value register as:

`Estimation of SNR on last packet received in two’s compliment format multiplied by 4.`

The only difference between the two is the misspelling in the 127x data sheet. This raises the question, why does the library return the value in different ways?

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/inconsistent-reported-signal-on-oled-screen/2340/2

**Comment by garthvh** [comment]
@thebentern Closing this as it seems related to the 1262 power updates

**Comment by vemanthchandrap** [comment]
Hey guys, hope you are doing good. this is my first project. I took two Lilygo tbeam axp2101-v1.2 for my Lora project. I need to find RSSI and SNR values. i have codes for transmitter and receiver and i am using LoRa library by sandeep mistry in arduino ide. I used TTGO LoRa32 OLED as my board and i didn't get any error in the output, but i can't see any output values in serial monitor. anyone can help me with this. Please help me I am clueless, any chances I need to do to get the values on serial monitor. I used the codes from https://randomnerdtutorials.com/ttgo-lora32-sx1276-arduino-ide/

output:
Sketch uses 280941 bytes (21%) of program storage space. Maximum is 1310720 bytes.
Global variables use 22388 bytes (7%) of dynamic memory, leaving 272524 bytes for local variables. Maximum is 294912 bytes.
esptool.py v4.5.1
Serial port COM11
Connecting....
Chip is ESP32-D0WDQ6-V3 (revision v3.1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 34:98:7a:6b:f7:a0
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x00008000 to 0x00008fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x00054fff...
Compressed 17568 bytes to 12204...
Writing at 0x00001000... (100 %)
Wrote 17568 bytes (12204 compressed) at 0x00001000 in 0.5 seconds (effective 295.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.1 seconds (effective 391.8 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 493.3 kbit/s)...
Hash of data verified.
Compressed 281312 bytes to 152630...
Writing at 0x00010000... (10 %)
Writing at 0x0001d278... (20 %)
Writing at 0x000250b1... (30 %)
Writing at 0x0002a328... (40 %)
Writing at 0x0002f84c... (50 %)
Writing at 0x00034dac... (60 %)
Writing at 0x0003d6a4... (70 %)
Writing at 0x0004812f... (80 %)
Writing at 0x0004d6ff... (90 %)
Writing at 0x00052ebb... (100 %)
Wrote 281312 bytes (152630 compressed) at 0x00010000 in 2.6 seconds (effective 881.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
